###
---
- set_fact:
    map_public: "{{ subnet['public'] }}"
- set_fact:
    access: "{% if (map_public == true) %}public{% else %}private{% endif %}"

- name: Create subnet
  register: subnet_facts
  ec2_vpc_subnet:
    region: "{{ region }}"
    vpc_id: "{{ vpc_id }}"
    az: "{{ region }}{{ subnet['az'] }}"
    cidr: "10.0.{{ subnet['cidr'] }}.0/24"
    map_public: "{{ map_public }}" 
    resource_tags:
      Name: "{{ env }}-{{ access }}-{{ subnet['az'] }}"

# ex. subnet_public_a
- set_fact:
    "subnet_{{ access }}_{{ subnet['az'] }}": "{{ subnet_facts['subnet'] }}"
  
