---
- set_fact:
    map_public: "{{ subnet['public'] }}"
- set_fact:
    access: "{% if (map_public == true) %}public{% else %}private{% endif %}"

- name: Delete subnet
  ec2_vpc_subnet:
    state: absent
    region: "{{ region }}"
    vpc_id: "{{ vpc_id }}"
    az: "{{ region }}{{ subnet['az'] }}"
    cidr: "10.0.{{ subnet['cidr'] }}.0/24"
    resource_tags:
      Name: "{{ env }}-{{ access }}-{{ subnet['az'] }}"


