###
---
######
# Cloudformation
# Doc: 'https://docs.ansible.com/ansible/latest/modules/cloudformation_module.html'
######
- name: Handle network stack
  register: network_stack
  cloudformation:
    stack_name: "{{ env }}-network-stack"
    state: "{{ state }}"
    region: "{{ vpc['region'] }}"
    disable_rollback: no
    template: "tasks/network-stack.yml"
    template_parameters:
      Environment: "{{ env }}"
      Region: "{{ vpc['region'] }}"
      CidrBlock: "10.0.0.0/16"
      NGW: "{{ vpc['ngw'] }}"

- name: Handle web stack
  cloudformation:
    stack_name: "{{ env }}-web-stack"
    state: "{{ state }}"
    region: "{{ vpc['region'] }}"
    disable_rollback: no
    on_create_failure: DELETE
    template: "tasks/web-stack.yml"
    template_parameters:
      NetworkStackName: "{{ env }}-network-stack"